format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$nix_shell\
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[python]
symbol = " "
format = "[$symbol$version]($style) "

[nodejs]
symbol = " "
format = "[$symbol$version]($style) "

[rust]
symbol = " "
format = "[$symbol$version]($style) "

[golang]
symbol = " "
format = "[$symbol$version]($style) "

[nix_shell]
symbol = " "
format = "[$symbol$state]($style) "

[cmd_duration]
min_time = 2_000
format = "[$duration]($style) "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
